language: php

matrix:
    include:
        - php: 5.6
        - php: 7.0
        - php: hhvm
        - php: nightly

cache:
    directories:
        - $HOME/.composer/cache

install:
    - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction

script:
    - phpunit --verbose --coverage-clover build/logs/clover.xml
    - phpenv config-rm xdebug.ini || return 0

after_script:
  - CODECLIMATE_REPO_TOKEN="e2e9d435955a38f76c397686cadd6b99f37b2dd595b066878db3240448e010aa" vendor/bin/test-reporter --stdout > codeclimate.json
  - "curl -X POST -d @codeclimate.json -H 'Content-Type: application/json' -H 'User-Agent: Code Climate (PHP Test Reporter v0.1.1)' https://codeclimate.com/test_reports"

addons:
  code_climate:
    repo_token: e2e9d435955a38f76c397686cadd6b99f37b2dd595b066878db3240448e010aa

after_success:
    - php vendor/bin/coveralls -v